name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install musl-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools

    - name: Prepare workspace
      run: |
        set -x
        install -d $GITHUB_WORKSPACE/go/src/s3-sftp-proxy $GITHUB_WORKSPACE/go/bin
        shopt -s extglob dotglob
        mv !(go) $GITHUB_WORKSPACE/go/src/s3-sftp-proxy/
        ls -lR $GITHUB_WORKSPACE/
      env:
        GOPATH: $GITHUB_WORKSPACE/go

    # - name: Get dependencies
    #   run: |
    #     set -x
    #     go get -v -t -d ./...
    #     if [ -f Gopkg.toml ]; then
    #         install -d $GOPATH/bin
    #         curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    #         $GOPATH/bin/dep ensure
    #     fi
    #   env:
    #     GOPATH: /home/runner/go

    # - name: Build libc version
    #   run: go build -v . -o s3-sftp-proxy-libc

    # - name: Build musl version
    #   run: CC=/usr/bin/musl-gcc go build -v . -o s3-sftp-proxy-musl
