name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install musl-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools

    - name: Prepare workspace
      run: |
        set -x
        export GOPATH=$GITHUB_WORKSPACE/go
        install -d $GOPATH/src/s3-sftp-proxy $GOPATH/bin $GOPATH/output
        shopt -s extglob dotglob
        mv !(go) $GOPATH/src/s3-sftp-proxy/

    - name: Get dependencies
      run: |
        set -x
        export GOPATH=$GITHUB_WORKSPACE/go
        cd $GOPATH/src/s3-sftp-proxy/
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            $GOPATH/bin/dep ensure
        fi

    - name: Build libc version
      run: |
        export GOPATH=$GITHUB_WORKSPACE/go
        cd $GOPATH/src/s3-sftp-proxy/
        go build -v -o $GOPATH/output/s3-sftp-proxy-libc

    - name: Build musl version
      run: |
        export GOPATH=$GITHUB_WORKSPACE/go
        export CC=/usr/bin/musl-gcc
        export CGO_ENABLED=0
        cd $GOPATH/src/s3-sftp-proxy/
        go build -v -o $GOPATH/output/s3-sftp-proxy-musl
